// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServerApp.Models;

#nullable disable

namespace ServerApp.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230828123357_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.10");

            modelBuilder.Entity("ServerApp.Models.Tender", b =>
                {
                    b.Property<long>("TenderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Elect")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<bool>("PageFlag")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TenderAccessDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TenderDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenderDesk")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TenderEndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenderName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("TenderNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenderPictUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TenderStartDate")
                        .HasColumnType("TEXT");

                    b.Property<double>("Width")
                        .HasColumnType("REAL");

                    b.HasKey("TenderId");

                    b.ToTable("Tenders");
                });

            modelBuilder.Entity("ServerApp.Models.TenderCreate", b =>
                {
                    b.Property<long>("TenderCreateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NameTenderCreations")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("TenderCreateNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenderCreateUnit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TenderCreationsCategory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TenderDeskCreations")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TenderCreateId");

                    b.ToTable("TendersCreate");
                });
#pragma warning restore 612, 618
        }
    }
}
